# Generated by Django 4.2.5 on 2023-09-11 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlistings_comments_bids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionlistings',
            options={'verbose_name_plural': 'Auction listings'},
        ),
        migrations.AlterModelOptions(
            name='bids',
            options={'verbose_name_plural': 'Bids'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
