# Generated by Django 4.2.5 on 2023-09-12 01:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auctionlistings_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='watchlisted_by',
            field=models.ManyToManyField(null=True, related_name='watchlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
