# Generated by Django 4.2.5 on 2023-09-12 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auctionlistings_watchlisted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='watchlisted_by',
            field=models.ManyToManyField(related_name='watchlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
