# Generated by Django 4.2.5 on 2023-09-12 13:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auctionlistings_watchlisted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winning_bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='category',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='current_bid',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
